name: Run linters and tests on push

on: ["push"]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      # clones repository code into the job runner (ubuntu)
      - uses: actions/checkout@v3
      
      - name: Run mypy
        run: mypy .