name: Run linters and tests on push

on: ["push"]

# jobs are run on runners - single-use computers. 
# Before running any useful job steps,
# we need to configure the python environment on the runner.
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      # clones repository code into the job runner (ubuntu)
      - uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      # We don't use conda environments here because we only need a single
      # environment to run the job. We will not need other environments, 
      # so we can install all dependecies to the global python environment.
      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.poetry/bin:$PATH"
          poetry --version

      - name: Install dependencies
        run: poetry install
      
      - name: Run mypy
        run: poetry run mypy .

      - name: Run pylint
        run: poetry run pylint flight_route_planner tests

      - name: Run unit tests
        run: poetry run pytest tests